name: Deploy to S3

on:
  push:
    paths:
      - frontend/**
    branches:
      - main

jobs:
  sync_to_s3:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-south-1
      LOCAL_FOLDER: frontend/out
      S3_BUCKET: bettermort/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build the App
        uses: actions/setup-node@v4
        with:
          node-version: 20
        run: npm ci
        run: npm run build

      - name: Sync to S3
        run: |
          aws s3 sync ${{ env.LOCAL_FOLDER }} s3://${{ env.S3_BUCKET }}
