name: Deploy to S3

on:
  push:
    branches:
      - main

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  sync_to_s3:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-south-1
      LOCAL_FOLDER: frontend/out/
      S3_BUCKET: bettermort/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::647256487653:role/gha-role
          role-session-name: gha-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Sync to S3
        run: |
          aws s3 sync ${{ env.LOCAL_FOLDER }} s3://${{ env.S3_BUCKET }}
